#### Task 1: Unit Converter

In [7]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'm_to_ft' or 'ft_to_m'.

    Returns:
        float: The converted length value.
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'm_to_ft' or 'ft_to_m'.")


def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'kg_to_lbs' or 'lbs_to_kg'.

    Returns:
        float: The converted weight value.
    """
    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'kg_to_lbs' or 'lbs_to_kg'.")


def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'l_to_gal' or 'gal_to_l'.

    Returns:
        float: The converted volume value.
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'l_to_gal' or 'gal_to_l'.")


def unit_converter():
    """
    Interactive unit converter for length, weight, and volume.
    Prompts the user to choose a conversion type and input a value.
    Handles invalid input gracefully using try-except.
    """
    print("=== Unit Converter ===")
    print("1. Length  (meters <-> feet)")
    print("2. Weight  (kg <-> lbs)")
    print("3. Volume  (liters <-> gallons)")

    try:
        category = input("Choose category (1/2/3): ").strip()
        value = float(input("Enter the value to convert: "))

        if category == '1':
            print("  a. Meters to Feet\n  b. Feet to Meters")
            sub = input("Choose (a/b): ").strip().lower()
            direction = 'm_to_ft' if sub == 'a' else 'ft_to_m'
            result = convert_length(value, direction)
            unit_in, unit_out = ('m', 'ft') if sub == 'a' else ('ft', 'm')

        elif category == '2':
            print("  a. Kilograms to Pounds\n  b. Pounds to Kilograms")
            sub = input("Choose (a/b): ").strip().lower()
            direction = 'kg_to_lbs' if sub == 'a' else 'lbs_to_kg'
            result = convert_weight(value, direction)
            unit_in, unit_out = ('kg', 'lbs') if sub == 'a' else ('lbs', 'kg')

        elif category == '3':
            print("  a. Liters to Gallons\n  b. Gallons to Liters")
            sub = input("Choose (a/b): ").strip().lower()
            direction = 'l_to_gal' if sub == 'a' else 'gal_to_l'
            result = convert_volume(value, direction)
            unit_in, unit_out = ('L', 'gal') if sub == 'a' else ('gal', 'L')

        else:
            print("Invalid category selected.")
            return

        print(f"Result: {value} {unit_in} = {result:.4f} {unit_out}")

    except ValueError as e:
        print(f"Error: {e}. Please enter a valid numeric value.")


# Demo without interactive input
print(" Results ")
print(f"5 m -> ft : {convert_length(5, 'm_to_ft'):.4f} ft")
print(f"70 kg -> lbs : {convert_weight(70, 'kg_to_lbs'):.4f} lbs")
print(f"3 L -> gal : {convert_volume(3, 'l_to_gal'):.4f} gal")


 Results 
5 m -> ft : 16.4042 ft
70 kg -> lbs : 154.3234 lbs
3 L -> gal : 0.7925 gal


TASK 2: List Mathematical Operations

In [9]:
def compute_sum(numbers):
    """
    Computes the sum of a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The sum of all elements.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers)


def compute_average(numbers):
    """
    Computes the average of a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The average (mean) of all elements.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The maximum element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return max(numbers)


def compute_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The minimum element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return min(numbers)


def math_operations_menu():
    """
    Interactive menu for performing mathematical operations on a user-supplied list.
    Handles invalid input and empty lists with try-except.
    """
    print("=== List Math Operations ===")
    print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

    try:
        choice = input("Choose operation (1/2/3/4): ").strip()
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]

        ops = {'1': compute_sum, '2': compute_average,
               '3': compute_maximum, '4': compute_minimum}
        labels = {'1': 'Sum', '2': 'Average', '3': 'Maximum', '4': 'Minimum'}

        if choice not in ops:
            print("Invalid choice.")
            return

        result = ops[choice](numbers)
        print(f"{labels[choice]}: {result}")

    except ValueError as e:
        print(f"Error: {e}")


# Demo
nums = [4, 7, 2, 9, 1, 5]
print(" Results ")
print(f"List   : {nums}")
print(f"Sum    : {compute_sum(nums)}")
print(f"Average: {compute_average(nums)}")
print(f"Maximum: {compute_maximum(nums)}")
print(f"Minimum: {compute_minimum(nums)}")


 Results 
List   : [4, 7, 2, 9, 1, 5]
Sum    : 28
Average: 4.666666666666667
Maximum: 9
Minimum: 1


 Exercise on List Manipulation

In [10]:
# 1. Extract every other element
def extract_every_other(lst):
    """Returns every other element starting from the first."""
    return lst[::2]

# 2. Slice a sublist (inclusive end)
def get_sublist(lst, start, end):
    """Returns elements from index start to end (inclusive)."""
    return lst[start:end + 1]

# 3. Reverse a list using slicing
def reverse_list(lst):
    """Returns a reversed copy of the list using slicing."""
    return lst[::-1]

# 4. Remove first and last elements
def remove_first_last(lst):
    """Returns the list without its first and last elements."""
    return lst[1:-1]

# 5. Get first n elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

# 6. Extract last n elements
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

# 7. Extract elements in reverse order, skipping one, starting from second-to-last
def reverse_skip(lst):
    """Returns every second element starting from second-to-last, moving backward."""
    return lst[-2::-2]


# --- Tests ---
lst1 = [1, 2, 3, 4, 5, 6]
lst2 = [1, 2, 3, 4, 5]

print("1. Every other element    :", extract_every_other(lst1))     # [1,3,5]
print("2. Sublist [2:4] inclusive:", get_sublist(lst1, 2, 4))        # [3,4,5]
print("3. Reversed list          :", reverse_list(lst2))             # [5,4,3,2,1]
print("4. Remove first & last    :", remove_first_last(lst2))        # [2,3,4]
print("5. First 3 elements       :", get_first_n(lst2, 3))           # [1,2,3]
print("6. Last 2 elements        :", get_last_n(lst2, 2))            # [4,5]
print("7. Reverse skip           :", reverse_skip(lst1))             # [5,3,1]


1. Every other element    : [1, 3, 5]
2. Sublist [2:4] inclusive: [3, 4, 5]
3. Reversed list          : [5, 4, 3, 2, 1]
4. Remove first & last    : [2, 3, 4]
5. First 3 elements       : [1, 2, 3]
6. Last 2 elements        : [4, 5]
7. Reverse skip           : [5, 3, 1]


Exercise on Nested Lists

In [11]:
# 1. Flatten a nested list (one level)
def flatten(lst):
    """Flattens a one-level nested list into a single list."""
    return [item for sublist in lst for item in sublist]


# 2. Access a nested element by index path
def access_nested_element(lst, indices):
    """Returns the element at the position specified by the list of indices."""
    element = lst
    for i in indices:
        element = element[i]
    return element


# 3. Sum all elements in a nested list (any depth)
def sum_nested(lst):
    """Recursively sums all numbers in a nested list of arbitrary depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# 4. Remove a specific element from a nested list
def remove_element(lst, elem):
    """Removes all occurrences of elem from each sublist."""
    return [[x for x in sublist if x != elem] for sublist in lst]


# 5. Find maximum in a nested list (any depth)
def find_max(lst):
    """Recursively finds the maximum element in a nested list."""
    values = []
    for item in lst:
        if isinstance(item, list):
            values.append(find_max(item))
        else:
            values.append(item)
    return max(values)


# 6. Count occurrences of an element in a nested list
def count_occurrences(lst, elem):
    """Recursively counts how many times elem appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# 7. Deep flatten (any depth)
def deep_flatten(lst):
    """Recursively flattens a deeply nested list into a single flat list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


# 8. Average of all elements in a nested list
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


# --- Tests ---
print("1. Flatten         :", flatten([[1,2],[3,4],[5]]))                        # [1,2,3,4,5]
print("2. Access [1][2]   :", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))  # 6
print("3. Sum nested      :", sum_nested([[1,2],[3,[4,5]],6]))                   # 21
print("4. Remove 2        :", remove_element([[1,2],[3,2],[4,5]], 2))            # [[1],[3],[4,5]]
print("5. Find max        :", find_max([[1,2],[3,[4,5]],6]))                     # 6
print("6. Count 2         :", count_occurrences([[1,2],[2,3],[2,4]], 2))         # 3
print("7. Deep flatten    :", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))       # [1..8]
print("8. Average nested  :", average_nested([[1,2],[3,4],[5,6]]))               # 3.5


1. Flatten         : [1, 2, 3, 4, 5]
2. Access [1][2]   : 6
3. Sum nested      : 21
4. Remove 2        : [[1], [3], [4, 5]]
5. Find max        : 6
6. Count 2         : 3
7. Deep flatten    : [1, 2, 3, 4, 5, 6, 7, 8]
8. Average nested  : 3.5


TO-DO — NumPy Exercises

#### Problem 1: Array Creation

In [12]:
import numpy as np

# 1. Empty array 2x2
empty_arr = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_arr)

# 2. All-ones array 4x2
ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_arr)

# 3. Array filled with a fill value (e.g., 7), shape 3x3
filled_arr = np.full((3, 3), 7)
print("\n3. Full array (fill_value=7, shape 3x3):\n", filled_arr)

# 4. zeros_like — same shape as filled_arr
zeros_like_arr = np.zeros_like(filled_arr)
print("\n4. zeros_like (based on filled_arr):\n", zeros_like_arr)

# 5. ones_like — same shape as filled_arr
ones_like_arr = np.ones_like(filled_arr)
print("\n5. ones_like (based on filled_arr):\n", ones_like_arr)

# 6. Convert Python list to NumPy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. Converted list to numpy array:", np_array)


1. Empty 2x2 array:
 [[1.63064458e-315 0.00000000e+000]
 [4.94065646e-324 6.52771982e-310]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (fill_value=7, shape 3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like (based on filled_arr):
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. ones_like (based on filled_arr):
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Converted list to numpy array: [1 2 3 4]


#### Problem 2: Array Manipulation — Ranges and Indexing

In [13]:
import numpy as np

# 1. Values from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array 10-49:\n", arr1)

# 2. 3x3 matrix with values 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):\n", arr2)

# 3. 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", arr3)

# 4. Random array size 30, find mean
arr4 = np.random.random(30)
print("\n4. Random array (size 30) mean:", arr4.mean())

# 5. 10x10 random array — min and max
arr5 = np.random.random((10, 10))
print("\n5. 10x10 random array — min:", arr5.min(), "| max:", arr5.max())

# 6. Zero array size 10; replace 5th element (index 4) with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element = 1:\n", arr6)

# 7. Reverse the array
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((6, 6))
arr8[1:-1, 1:-1] = 0
print("\n8. Border=1, Inside=0:\n", arr8)

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard:\n", arr9)


1. Array 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30) mean: 0.4424655881422207

5. 10x10 random array — min: 0.0268894304091839 | max: 0.9931303355894383

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border=1, Inside=0:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Problem 3: Array Operations

In [14]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y:\n", x + y)

# 2. Subtract
print("\n2. x - y:\n", x - y)

# 3. Multiply by scalar
print("\n3. x * 3:\n", x * 3)

# 4. Square each element
print("\n4. x squared:\n", np.square(x))

# 5. Dot products
print("\n5a. Dot(v, w):", np.dot(v, w))
print("5b. Dot(x, v):\n", np.dot(x, v))
print("5c. Dot(x, y):\n", np.dot(x, y))

# 6. Concatenate
print("\n6a. x and y concatenated along rows (axis=0):\n", np.vstack((x, y)))
print("6b. v and w concatenated along column:\n", np.column_stack((v, w)))

# 7. Try concatenating x (2D) and v (1D)
print("\n7. Attempting np.concatenate(x, v):")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"   Error: {e}")
    print("   Explanation: x has shape (2,2) and v has shape (2,). They have"
          " different numbers of dimensions, so concatenation fails.")
    print("   Fix: reshape v to (1,2) first — np.concatenate((x, v.reshape(1,2)))")
    print("   Result:", np.concatenate((x, v.reshape(1, 2))))


1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5a. Dot(v, w): 219
5b. Dot(x, v):
 [29 77]
5c. Dot(x, y):
 [[19 22]
 [50 58]]

6a. x and y concatenated along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. v and w concatenated along column:
 [[ 9 11]
 [10 12]]

7. Attempting np.concatenate(x, v):
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Explanation: x has shape (2,2) and v has shape (2,). They have different numbers of dimensions, so concatenation fails.
   Fix: reshape v to (1,2) first — np.concatenate((x, v.reshape(1,2)))
   Result: [[ 1  2]
 [ 3  5]
 [ 9 10]]


#### Problem 4: Matrix Operations

In [15]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
product_AI = np.dot(A, A_inv)
print("1. A × A⁻¹ (should be Identity):\n", np.round(product_AI, decimals=10))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2a. AB:\n", AB)
print("2b. BA:\n", BA)
print("   AB == BA:", np.array_equal(AB, BA))  # Should be False

# 3. Prove (AB)^T = B^T * A^T
LHS = np.dot(A, B).T
RHS = np.dot(B.T, A.T)
print("\n3a. (AB)^T:\n", LHS)
print("3b. Bᵀ × Aᵀ:\n", RHS)
print("   (AB)ᵀ == BᵀAᵀ:", np.array_equal(LHS, RHS))  # Should be True

# --- Solve system of linear equations ---
# 2x - 3y + z = -1
# x  - y + 2z = -3
# 3x + y - z  =  9

coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])
constants = np.array([-1, -3, 9])

# Inverse method: X = A^-1 * B
coeff_inv = np.linalg.inv(coeff)
solution_inv = np.dot(coeff_inv, constants)
print("\n--- Linear System Solution (Inverse Method) ---")
print(f"x = {solution_inv[0]:.4f}, y = {solution_inv[1]:.4f}, z = {solution_inv[2]:.4f}")

# Using np.linalg.solve
solution_solve = np.linalg.solve(coeff, constants)
print("\n--- Linear System Solution (np.linalg.solve) ---")
print(f"x = {solution_solve[0]:.4f}, y = {solution_solve[1]:.4f}, z = {solution_solve[2]:.4f}")


1. A × A⁻¹ (should be Identity):
 [[1. 0.]
 [0. 1.]]

2a. AB:
 [[23 13]
 [51 29]]
2b. BA:
 [[36 44]
 [13 16]]
   AB == BA: False

3a. (AB)^T:
 [[23 51]
 [13 29]]
3b. Bᵀ × Aᵀ:
 [[23 51]
 [13 29]]
   (AB)ᵀ == BᵀAᵀ: True

--- Linear System Solution (Inverse Method) ---
x = 2.0000, y = 1.0000, z = -2.0000

--- Linear System Solution (np.linalg.solve) ---
x = 2.0000, y = 1.0000, z = -2.0000
